import type { Service, Industry, Project, Testimonial, FAQ, SiteSetting } from "@/types";
import { generateId, now } from "@/lib/utils";

export const DEFAULT_SETTINGS: SiteSetting = {
  heroHeading: "WE BUILD\nDIGITAL HOMES\nFOR SPORT",
  heroParagraph: "High-performance websites and digital experiences for gyms, fitness brands and sports organisations.",
  heroCta1Label: "START A PROJECT",
  heroCta1Link: "/contact",
  heroCta2Label: "VIEW OUR WORK",
  heroCta2Link: "/work",
  heroImageUrl: "",
  primaryEmail: "hello@fitlaunchmedia.com",
  phone: "",
  location: "",
  businessHours: "Monday – Friday, 9am – 6pm",
  contactCta: "Ready to build your digital home?",
  footerDescription: "FitLaunch Media builds high-performance websites and digital experiences for gyms, fitness brands and sports organisations.",
  footerCta: "START A PROJECT",
  globalSeoTitle: "FitLaunch Media — Premium Websites for Gyms & Sports Organisations",
  globalSeoDescription: "High-performance websites and digital experiences for gyms, fitness brands and sports organisations. Mobile-first, sport-focused, conversion-driven.",
  updatedAt: now(),
};

export const DEFAULT_SERVICES: Service[] = [
  {
    id: "svc-1",
    title: "Website Development",
    slug: "website-development",
    icon: "Monitor",
    shortDescription: "Bespoke, high-performance websites engineered for sport. Fast, mobile-first and built to convert.",
    longDescription: "We design and engineer premium websites that reflect the ambition and identity of your sports business. Every project is built from scratch — no templates, no shortcuts.",
    features: ["Custom design & development", "Mobile-first architecture", "Core Web Vitals optimised", "CMS-powered content", "Enquiry & lead capture", "SEO-ready structure"],
    ctaLabel: "Learn More",
    ctaLink: "/services",
    status: "PUBLISHED",
    order: 1,
    updatedAt: now(),
  },
  {
    id: "svc-2",
    title: "Booking Systems",
    slug: "booking-systems",
    icon: "CalendarCheck",
    shortDescription: "Streamlined class, session and appointment booking built directly into your digital experience.",
    longDescription: "Reduce admin and let members and clients book 24/7. We integrate purpose-built booking flows that match your business model.",
    features: ["Class & session booking flows", "Appointment scheduling", "Capacity management", "Booking confirmation systems", "Mobile-optimised experience", "Integration-ready architecture"],
    ctaLabel: "Learn More",
    ctaLink: "/services",
    status: "PUBLISHED",
    order: 2,
    updatedAt: now(),
  },
  {
    id: "svc-3",
    title: "Lead Generation",
    slug: "lead-generation",
    icon: "TrendingUp",
    shortDescription: "Conversion-optimised contact flows, enquiry systems and lead capture designed to bring more prospects to your door.",
    longDescription: "We build enquiry systems, landing pages and lead capture mechanisms that turn website visitors into qualified leads for your sports business.",
    features: ["Optimised enquiry forms", "Landing page development", "CTA architecture", "Form-to-CRM pathways", "Trial signup flows", "Contact workflow design"],
    ctaLabel: "Learn More",
    ctaLink: "/services",
    status: "PUBLISHED",
    order: 3,
    updatedAt: now(),
  },
  {
    id: "svc-4",
    title: "Membership Experiences",
    slug: "membership-experiences",
    icon: "Users",
    shortDescription: "Digital membership portals and member-facing experiences that build loyalty and reduce churn.",
    longDescription: "Give your members a digital home that reflects the quality of your facility. Member portals, content hubs and community spaces built for sports businesses.",
    features: ["Member portal design", "Content & resource hubs", "News & updates systems", "Community features", "Event & programme listing", "Member-facing dashboards"],
    ctaLabel: "Learn More",
    ctaLink: "/services",
    status: "PUBLISHED",
    order: 4,
    updatedAt: now(),
  },
  {
    id: "svc-5",
    title: "Sports Organisation Platforms",
    slug: "sports-organisation-platforms",
    icon: "Trophy",
    shortDescription: "Full digital platforms for leagues, federations, clubs and sports bodies — fixtures, results, teams and more.",
    longDescription: "Complex sports organisations need purpose-built digital infrastructure. We build platforms that manage fixtures, results, teams, coaches, sponsors and news.",
    features: ["Fixtures & results systems", "Team & squad pages", "Coach & staff profiles", "Sponsor & partner pages", "News & media systems", "Registration & event tools"],
    ctaLabel: "Learn More",
    ctaLink: "/services",
    status: "PUBLISHED",
    order: 5,
    updatedAt: now(),
  },
  {
    id: "svc-6",
    title: "Digital Growth",
    slug: "digital-growth",
    icon: "BarChart2",
    shortDescription: "Ongoing optimisation, performance monitoring and strategic digital development for sports businesses.",
    longDescription: "Digital success requires continuous improvement. We work with clients on an ongoing basis to optimise, evolve and grow their digital presence.",
    features: ["Performance monitoring", "SEO & content strategy", "Conversion optimisation", "Analytics & reporting setup", "Platform evolution", "Strategic digital support"],
    ctaLabel: "Learn More",
    ctaLink: "/services",
    status: "PUBLISHED",
    order: 6,
    updatedAt: now(),
  },
];

export const DEFAULT_INDUSTRIES: Industry[] = [
  {
    id: "ind-1",
    title: "Gyms",
    slug: "gyms",
    icon: "Dumbbell",
    description: "Membership-driven digital experiences that showcase your facility, capture leads and power bookings for modern gyms.",
    features: ["Membership sign-up flows", "Class booking systems", "PT & coach profiles", "Facility showcase", "Trial offer landing pages", "Member resources"],
    status: "PUBLISHED",
    order: 1,
    updatedAt: now(),
  },
  {
    id: "ind-2",
    title: "Boxing Clubs",
    slug: "boxing-clubs",
    icon: "Zap",
    description: "Powerful, disciplined websites that reflect the identity of boxing clubs — from grassroots to elite competition.",
    features: ["Class & session booking", "Coach & trainer profiles", "News & event listings", "Membership information", "Lead capture & trial flows", "Competition results"],
    status: "PUBLISHED",
    order: 2,
    updatedAt: now(),
  },
  {
    id: "ind-3",
    title: "Fitness Studios",
    slug: "fitness-studios",
    icon: "Activity",
    description: "Boutique and premium studio websites that communicate your methodology, community and programme with clarity.",
    features: ["Studio & class showcase", "Programme listings", "Instructor profiles", "Online booking", "Community content hub", "Event & workshop pages"],
    status: "PUBLISHED",
    order: 3,
    updatedAt: now(),
  },
  {
    id: "ind-4",
    title: "Football Academies",
    slug: "football-academies",
    icon: "CircleDot",
    description: "Digital platforms for football academies that present coaching staff, programmes, trials and club culture professionally.",
    features: ["Academy programme pages", "Coaching team profiles", "Trial & registration flows", "News & match reports", "Age group sections", "Sponsor & partner pages"],
    status: "PUBLISHED",
    order: 4,
    updatedAt: now(),
  },
  {
    id: "ind-5",
    title: "Sports Clubs",
    slug: "sports-clubs",
    icon: "Shield",
    description: "Community club websites that manage teams, fixtures, results, news, events and membership all in one place.",
    features: ["Fixtures & results", "Team & squad pages", "News & media hub", "Event management", "Membership information", "Club history & honours"],
    status: "PUBLISHED",
    order: 5,
    updatedAt: now(),
  },
  {
    id: "ind-6",
    title: "Sports Organisations",
    slug: "sports-organisations",
    icon: "Building2",
    description: "Scalable digital platforms for governing bodies, leagues and federations managing multiple teams, competitions and stakeholders.",
    features: ["League & competition management", "Multi-team architecture", "Sponsor & partner hub", "Official communications", "Registration systems", "Governance & documentation"],
    status: "PUBLISHED",
    order: 6,
    updatedAt: now(),
  },
];

export const DEFAULT_PROJECTS: Project[] = [
  {
    id: "proj-1",
    title: "Metro Performance Gym",
    slug: "metro-performance-gym",
    industry: "Gym",
    services: ["Website Development", "Booking Systems", "Lead Generation"],
    summary: "A full digital rebuild for a modern performance gym. We created a membership-first website with integrated booking flows, PT profiles and conversion-optimised trial offer pages.",
    approvedResults: "This is a FitLaunch CONCEPT/DEMO project. Results shown are illustrative only and do not represent a real client engagement.",
    coverImage: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&h=500&fit=crop&q=80",
    galleryImages: [],
    status: "DEMO",
    featured: true,
    order: 1,
    publishDate: "2026-01-01",
    updatedAt: now(),
  },
  {
    id: "proj-2",
    title: "Apex Boxing Academy",
    slug: "apex-boxing-academy",
    industry: "Boxing Club",
    services: ["Website Development", "Membership Experiences", "Lead Generation"],
    summary: "Brand-led website for a competitive boxing academy. The project centred on communicating coaching credentials, class structure and generating trial sign-ups through optimised lead capture.",
    approvedResults: "This is a FitLaunch CONCEPT/DEMO project. Results shown are illustrative only and do not represent a real client engagement.",
    coverImage: "https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=800&h=500&fit=crop&q=80",
    galleryImages: [],
    status: "DEMO",
    featured: true,
    order: 2,
    publishDate: "2026-01-01",
    updatedAt: now(),
  },
  {
    id: "proj-3",
    title: "Velocity Football Academy",
    slug: "velocity-football-academy",
    industry: "Football Academy",
    services: ["Website Development", "Sports Organisation Platforms", "Lead Generation"],
    summary: "Comprehensive digital platform for a regional football academy. Features include age-group programme pages, coaching team profiles, trial registration flows and news management.",
    approvedResults: "This is a FitLaunch CONCEPT/DEMO project. Results shown are illustrative only and do not represent a real client engagement.",
    coverImage: "https://images.unsplash.com/photo-1553778263-73a83bab9b0c?w=800&h=500&fit=crop&q=80",
    galleryImages: [],
    status: "DEMO",
    featured: true,
    order: 3,
    publishDate: "2026-01-01",
    updatedAt: now(),
  },
];

export const DEFAULT_TESTIMONIALS: Testimonial[] = [
  {
    id: "test-1",
    name: "J. Hargreaves",
    organisation: "Ironworks Performance Gym",
    industry: "Gym",
    role: "Head Coach & Owner",
    text: "FitLaunch understood exactly what a gym website needs to do. The new site looks sharp and brings in enquiries week after week.",
    rating: 5,
    date: "2026-01-01",
    featured: true,
    status: "DEMO",
    order: 1,
    updatedAt: now(),
  },
  {
    id: "test-2",
    name: "M. Okafor",
    organisation: "Southside Boxing Club",
    industry: "Boxing Club",
    role: "Club Director",
    text: "Professional, precise and sport-focused. They built us a platform that represents the club properly and keeps our members informed.",
    rating: 5,
    date: "2026-01-01",
    featured: true,
    status: "DEMO",
    order: 2,
    updatedAt: now(),
  },
  {
    id: "test-3",
    name: "R. Callahan",
    organisation: "United FC Academy",
    industry: "Football Academy",
    role: "Academy Manager",
    text: "We needed more than a basic website — we needed a platform. FitLaunch delivered exactly that, on time and without compromise.",
    rating: 5,
    date: "2026-01-01",
    featured: true,
    status: "DEMO",
    order: 3,
    updatedAt: now(),
  },
  {
    id: "test-4",
    name: "A. Singh",
    organisation: "Form Fitness Studio",
    industry: "Fitness Studio",
    role: "Studio Founder",
    text: "The attention to detail in the design is outstanding. Our studio now has an online presence that truly reflects the quality of what we do.",
    rating: 5,
    date: "2026-01-01",
    featured: false,
    status: "DEMO",
    order: 4,
    updatedAt: now(),
  },
  {
    id: "test-5",
    name: "T. Williams",
    organisation: "City Athletic Club",
    industry: "Sports Club",
    role: "Club Secretary",
    text: "Managing fixtures, results and team pages used to be a pain. Now it's all in one place and our members can find everything they need.",
    rating: 5,
    date: "2026-01-01",
    featured: false,
    status: "DEMO",
    order: 5,
    updatedAt: now(),
  },
  {
    id: "test-6",
    name: "D. Brannigan",
    organisation: "Regional Sports Council",
    industry: "Sports Organisation",
    role: "Digital Lead",
    text: "A genuinely sophisticated build. FitLaunch handled the complexity of a multi-club organisation without blinking. Impressive work.",
    rating: 5,
    date: "2026-01-01",
    featured: false,
    status: "DEMO",
    order: 6,
    updatedAt: now(),
  },
  {
    id: "test-7",
    name: "K. Donovan",
    organisation: "Peak S&C",
    industry: "Strength & Conditioning",
    role: "Lead S&C Coach",
    text: "Clean, fast and exactly right for what we do. Our client enquiries increased meaningfully after the new site launched.",
    rating: 5,
    date: "2026-01-01",
    featured: false,
    status: "DEMO",
    order: 7,
    updatedAt: now(),
  },
  {
    id: "test-8",
    name: "L. Fontaine",
    organisation: "Elevate Athletic Performance",
    industry: "Athletic Performance",
    role: "Performance Director",
    text: "FitLaunch built us a platform that speaks the language of elite sport. It positions us exactly where we need to be.",
    rating: 5,
    date: "2026-01-01",
    featured: false,
    status: "DEMO",
    order: 8,
    updatedAt: now(),
  },
];

export const DEFAULT_FAQS: FAQ[] = [
  {
    id: "faq-1",
    question: "What types of sports businesses do you work with?",
    answer: "We work with gyms, boxing clubs, fitness studios, football academies, sports clubs, sports organisations and other fitness and athletic businesses. If you're in the business of sport, we can build your digital presence.",
    category: "General",
    order: 1,
    status: "PUBLISHED",
    updatedAt: now(),
  },
  {
    id: "faq-2",
    question: "Do you use templates or build from scratch?",
    answer: "Every FitLaunch project is built from scratch. We don't use generic templates. Your website is designed and engineered specifically for your brand, your audience and your goals.",
    category: "Process",
    order: 2,
    status: "PUBLISHED",
    updatedAt: now(),
  },
  {
    id: "faq-3",
    question: "How long does a project take?",
    answer: "Project timelines depend on scope and complexity. We'll give you a clear timeline during the discovery phase before any work begins. We don't provide generic estimates without understanding your specific requirements.",
    category: "Process",
    order: 3,
    status: "PUBLISHED",
    updatedAt: now(),
  },
  {
    id: "faq-4",
    question: "Will I be able to update my own website?",
    answer: "Yes. We build every website with a content management system so you can update your own content — news, schedules, team information, images and more — without any technical knowledge.",
    category: "Technical",
    order: 4,
    status: "PUBLISHED",
    updatedAt: now(),
  },
  {
    id: "faq-5",
    question: "Do you handle SEO?",
    answer: "Yes. Every website we build is structured for search visibility from the ground up — semantic HTML, metadata, site speed, mobile optimisation and relevant content architecture. We build search-ready websites as standard.",
    category: "Technical",
    order: 5,
    status: "PUBLISHED",
    updatedAt: now(),
  },
  {
    id: "faq-6",
    question: "Can you integrate booking systems?",
    answer: "Yes. We design and build booking flows, class scheduling systems and appointment management as part of our project work. We'll discuss your specific booking requirements during discovery.",
    category: "Services",
    order: 6,
    status: "PUBLISHED",
    updatedAt: now(),
  },
  {
    id: "faq-7",
    question: "How do I start a project?",
    answer: "Use the Start a Project button to submit an enquiry, or use our Project Configurator to outline your requirements. We'll review your information and get back to you to arrange an initial conversation.",
    category: "General",
    order: 7,
    status: "PUBLISHED",
    updatedAt: now(),
  },
  {
    id: "faq-8",
    question: "What does a FitLaunch website cost?",
    answer: "We don't publish generic pricing because every project is different. Costs depend on scope, features and complexity. Contact us to discuss your requirements and we'll provide transparent project information.",
    category: "General",
    order: 8,
    status: "PUBLISHED",
    updatedAt: now(),
  },
];
